teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 1.0
      y: 1.0
    scale_linear_turbo:
      x: 0.6
      y: 0.6

      
    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 2.5

    enable_button: 9
    # enable_turbo_button: 10